### ISSUE TITLE
Request for new package

### ISSUE THREAD

**Issue by alefeld** [cms-analysis/CombineHarvester#146]
Hello,

I would like a package to be created for the ND-OSU Top EFT analysis. We would like to begin using CombineHarvester to create our datacards. The documentation instructed me to create an issue here. Let me know how I can help with this process.

Best,
Anthony Lefeld

**Comment by ajgilbert** [comment]
Hi Anthony, sorry I missed this. These days it's probably easier to just to fork this repo and add what you need yourself (can copy one of the existing packages to get started if necessary). Then if along the way you make any developments you think are useful for other analyses, we'd gladly accept a pull request back into the main repo. cheers, Andrew

**Comment by alefeld** [comment]
Hey Andrew,

That sounds good. I think that's all I need, as well. Thanks!

Best,
Tony
