### ISSUE TITLE
Conflicts between scripts

### ISSUE THREAD

**Issue by swertz** [cms-analysis/CombineHarvester#179]
Hi,

It seems there are several `plot1DScan.py` files in the `script` directories of the various sub-packages... When running `scram` these get copied to the CMSSW `bin` folder in a random order and overwrite the ["main"](https://github.com/cms-analysis/CombineHarvester/blob/master/CombineTools/scripts/plot1DScan.py) script, which is clearly undesirable. What's more, [at least one](https://github.com/cms-analysis/CombineHarvester/blob/master/HTTSM2016/scripts/plot1DScan.py) is not an executable file, so it's not even found as a command.

It could be the case also for other scripts, I haven't checked. I can submit a PR to rename them but perhaps you have another preferred solution?

**Comment by swertz** [comment]
I'm afraid this won't be sufficient, as all these other `*/scripts/plot1DScan.py` files will still be copied over to the `$CMSSW_BASE/bin` folder and potentially overwrite the main, executable script...

**Comment by adewit** [comment]
Ah sorry, I was under the impression that somehow the executables were written again but I see now that it's not the case. Pure luck that I've always dodged this bullet apparently ;-) Then yes, don't see another option than to rename the modified versions (while still making sure they are not executable so at least all those versions can still have a common name).
