### ISSUE TITLE
`RestoreBinning` does not properly work for some binnings, e.g. DNN scores?

### ISSUE THREAD

**Issue by pfackeldey** [cms-analysis/CombineHarvester#296]
Dear CombineHarvester experts,

we noticed an unexpected behaviour of the `PostFitShapesFromWorkspace` tool, when adding the datacard of a DNN score (0..1) for rebinning purposes:

The rebinned histogram had only as bin content the content of the first bin of the e.g. [`prefit_shapes`](https://github.com/cms-analysis/CombineHarvester/blob/610d8ded8d1f71ed4db4d634cd9e2d7b8ae7b560/CombineTools/bin/PostFitShapesFromWorkspace.cpp#L221).

Is this behaviour known?

(omitting the rebinning option via `-d` works fine and yields the expected output)

Best, Peter

**Comment by ajgilbert** [comment]
Hi Peter,

Can you tell us which branch/tag you are using? And if you can prepare a minimal example for us to reproduce that would be helpful. The bug may be something to do with matching up the categories between the workspace and the datacard, or it may be to do with the format of the datacard inputs (do you use TH1s for the DNN score distribution?)
