### ISSUE TITLE
CreateAxisHist function

### ISSUE THREAD

**Issue by miguelgallo** [cms-analysis/CombineHarvester#301]
The lines 473, 474, 478 and 480
min = float(x)
max = float(y) 
Should be changed to:
min = float(x.value)
max = float(x.value)

The way it's now it's not working, since x is not a number or a string, it is a ctypes.c_double object.

**Comment by adewit** [comment]
Thanks for reporting - in case you already made the changes in your local copy, can you make a PR?

**Comment by miguelgallo** [comment]
You welcome! I'll try doing the PR asap.

**Comment by adewit** [comment]
Fixed by #302
