### ISSUE TITLE
ParseDatacard with RooDataHist inputs

### ISSUE THREAD

**Issue by giacomoortona** [cms-analysis/CombineHarvester#69]
I’m trying to (gradually) switch to combineHarvester for the hh->bbtautau analyses, but it seems I’m not able to use it to parse a datacard/workspace with RooDataHist objects, do you know if this is a known feature, or if there’s something special to do to load RooDataHists in combineHarvester?

If you please, let me describe a bit in detail what is going on.
You can find here: 
/afs/cern.ch/user/g/gortona/public/4Andrew/cards_MuTauprova/HHSM2b0jMcutBDTMT2/hh_2_C2_LHHSM_13TeV.txt
a simplified card with just few backgrounds and no shape systematics. It can be linked to either a file with one TH1F per process or to a file with a workspace where shapes are stored as RooDataHists (both files are in the same folder).
text2workspace works properly, so the card should be fine, and indeed when I parse the card linking it to the TH1Fs all goes through properly. The script I am using is “harvesta.py” in the same folder.
But when I link the card to the workspace, I hit "Problem: RooAbsData not found in workspace”.
I tried to dig a bit, and it seems that in loading the workspace into combineHarvester the datasets names are lost. Adding mapping.ws->Print() at line 319 of combineHarvester.cc prints out the message below, but unfortunately I couldn’t track the origin of this behaviour more than this.

Did this already happen to you? Do you know if I’m doing anything wrong or if is there any way to fix this behaviour?

Thank you a lot,
Giacomo

mapping.ws->Print()
```

RooWorkspace(w) w contents

variables
---------
(CMS_HHbbtt_scale_tau,MT2)

p.d.f.s
-------
RooHistPdf::ggHH_hbbhtt[ pdfObs=(MT2) ] = 0

datasets
--------
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
RooDataHist::(MT2)
```
PS I’m using combineHarvester with combine v6.3.0 under CMSSW_7_4_7

**Comment by ajgilbert** [comment]
Right, indeed there's a bug in the version of RooFit we're using at the moment that causes the dataset names to be lost. A temporary workaround is to put:
cmb1.SetFlag('workspaces-use-clone', True)
before parsing the datacard. By the way: gmN uncertainties aren't supported correctly at the moment but I'll fix this soon.
