### ISSUE TITLE
Negative bin no longer put to zero when importing shapes

### ISSUE THREAD

**Issue by blinkseb** [cms-analysis/CombineHarvester#74]
Hi,

I noticed recently that negative bin are no longer put to zero. After looking at the code, the reason is that the line is commented? See https://github.com/cms-analysis/CombineHarvester/blob/1fd2a802008949f1035003d562e04d486be62c6c/CombineTools/src/CombineHarvester.cc#L400

It's pointless to have a flag to control this feature is the code is commented :)

**Comment by ajgilbert** [comment]
Hi Sébastien,

So my excuse here is that the use of these flags is not officially supported ;-) but you have a fair point that the current behaviour doesn't make any sense. 

The intended behaviour was by default to only warn the user about negative bins and not correct them, unless the flag was set. I'll fix this shortly.

cheers, Andrew

**Comment by blinkseb** [comment]
Cool, thanks a lot :+1:
